### ISSUE TITLE
Requires Python 3.8.6

### ISSUE THREAD

**Issue by BadUserHater** [MatthewDevelopment/slashcmds.py#2]
You should mention in the README document that in order to install the slash package mentioned, you need Python version 3.8.6 or higher.

**Comment by MDiscordDev** [comment]
I saw your other issue and this has been resolved. I have 2 files now. One for discord.py 1.7.x and one for discord.py 2.0 like you said. Also apperently discord.py 2.0 requires Python 3.8 or newer now so I will keep this in mind.

**Comment by MatthewDevelopment** [comment]
I have modified the README file so this issue is now resolved
